# Generated by Django 4.2.28 on 2026-02-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('income', 'Income'), ('housing_shelter', 'Housing/Shelter'), ('transportation', 'Transportation'), ('shopping_personal_care', 'Shopping/Personal Care'), ('health_medical', 'Health & Medical'), ('entertainment', 'Entertainment'), ('debt_finance', 'Debt & Finance'), ('savings_investments', 'Savings & Investments')], default='income', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
